### ISSUE TITLE
RESTful interface to DB

### ISSUE THREAD

**Issue by JamesKunstle** [oss-aspen/8Knot#133]
On audit from @codekow we should use a RESTful interface to our Augur instance (recommendation was postgrest).

**Comment by jberkus** [comment]
@codekow, can you provide the backing detail/reasoning for this recommendation? I don't have access to the audit.

**Comment by codekow** [comment]
@jberkus In general access to a raw DB is avoided when traversing the internet or unknown networks.

Looking at the example of most data shared by IT companies it has become the best practice to provide access to data via a RESTful interface. This is a common abstraction used to aid in development of cloud based applications.

Does this answer your question?

**Comment by jberkus** [comment]
@codekow we're actually using a proxy, for that reason.

Cali and Sean are figuring out if having REST endpoints will help them with development, and if so, what kind.

If they want to try Postgrest -- do you know how to secure it properly?

**Comment by jberkus** [comment]
> Are you talking about pgBouncer? I don't understand what "reason" you are referring to?

That was in reference to "exposing a raw database to the internet".

I talked to Cali about the rest of this at SCALE.  Because the schema is elaborate and fairly confusing, they'll want to expose stuff via REST that presents more "synthetic" views of the data, rather than exposing the tables directly.  It turns out that the Augur backend app itself also has an incomplete Rest API.

**Comment by cdolfi** [comment]
@JamesKunstle can this be closed?

**Comment by JamesKunstle** [comment]
@cdolfi yeah not our problem
