### ISSUE TITLE
cut off time series at current time

### ISSUE THREAD

**Issue by JamesKunstle** [oss-aspen/8Knot#296]
some repos have future dates in their issues, PRs- only show stuff from the past.

**Comment by cdolfi** [comment]
@JamesKunstle Ive started to work on this and curious if you have any suggestions on what I am running into. After thinking about it, my initial reaction was to drop this information at the query file level instead of needing to do it in each visualization. I tried implementing it by adding a where clause to the query itself and also dropping it in the for loop using "c_df = c_df[c_df.author_timestamp <= dt.date.today()]" (commits query specific but would apply to all w different column). Both options after pruning is getting stuck and the worker is not completing. Any thoughts on this?

**Comment by cdolfi** [comment]
@JamesKunstle Its getting stuck trying to run `c_df = c_df[c_df.author_timestamp < dt.date.today()]`which is very strange as we use the same method in some of our visualization. (app works all good on everything except the query im messing with)

**Comment by JamesKunstle** [comment]
@cdolfi 
is c_df.author_timestamp a datetime timestamp object? 
If the process is hanging then it might be that it's failing silently because the two objects aren't comparable.

**Comment by cdolfi** [comment]
@JamesKunstle should have specified but also have a `c_df["author_timestamp"] = pd.to_datetime(c_df["author_timestamp"], utc=True)` to change to dt

**Comment by JamesKunstle** [comment]
@cdolfi 
is it failing silently, hanging (not finishing), or another error?

**Comment by cdolfi** [comment]
@JamesKunstle hanging

**Comment by JamesKunstle** [comment]
@cdolfi 
huh... 
I have some debugging ideas but the issue itself is confusing.
