### ISSUE TITLE
BUG: Lines metrics are not working  

### ISSUE THREAD

**Issue by cdolfi** [oss-aspen/8Knot#308]

**Comment by JamesKunstle** [comment]
I'm pretty sure that this is because the # of concurrent connections to Augur, either from the client or the server, is limited. Therefore when all of the callbacks to fill in those metrics fire they try to execute at once and a few are denied.

The patch for this is to background the metrics tasks. They're currently non-backgrounded callbacks so when the DB rejects the connection they just exit as failed. 

Backgrounding them will require a tiny bit of cache logic but will be a good idea because then they will only ever have to fire once for each repo and be updated on cache restart. When the cache is hot the values per repo will be accessed and returned in constant time.

**Comment by cdolfi** [comment]
@JamesKunstle That makes sense, if we cant/dont have time to find a solution in the next few weeks we should temporarily take the metrics off of the hosted instance for OSSNA, RH Summit, etc

**Comment by JamesKunstle** [comment]
@cdolfi Yeah we can do that if need be.

**Comment by JamesKunstle** [comment]
UPDATE: 

We want to cache the metrics per repo- e.g. 'total number of commits for each repo selected' and then aggregate those statistics after caching. 

Therefore, the queries have to be updated to get the stats per selected repo rather than as one-shot for all repos.

**Comment by JamesKunstle** [comment]
GOAL: 

Try to use existing data from queries for metrics rather than using whole new queries.

**Comment by JamesKunstle** [comment]
finished as a part of Welcome page addition
