### ISSUE TITLE
Heatmap extension: Overall activity by (discussion below)

### ISSUE THREAD

**Issue by cdolfi** [oss-aspen/8Knot#515]
This will be the 3 installment of the heatmap visualizations. This will be a heatmap of the activity in the listed directories or folders

The discussion needs to be on what "activity" to be measured here. Options I see are: 

- PR opened 
- PR merged
- PR closed 
- Combination of the PR actions above 
- Commits

**Comment by JamesKunstle** [comment]
It'd be useful to identify which parts of a codebase receive the most attention, especially over the lifespan of a project, broken down by activity / time bucket.

This would be a visualization that's complementary to https://github.com/oss-aspen/Rappel/pull/234.

y-axis: file-tree documents at a certain level
x-axis: time-bins in months, from most recent collection back to start of project
z-axis: number of PRs relating to the files in the x-axis row.

Some parts of the codebase will likely have large bursts of activity (docs, config) but be silent for other long periods, whereas high traffic parts (internal functionality) are more likely to be consistently 'red hot' in the heatmap.

This is useful because, from 30k feet, the application user can see where the traffic in the community is centered, where people are spending the most time, and where they can look in the codebase to find the core of the functionality of the project.

This would also help community managers to identify areas of the codebase that aren't high-churn, that maybe should be. Consider the docs folder- if it hasn't been updated in 18mos, maybe that should be checked in on.


Cali: extension, z-axis could be LOC by toggle.
